### ISSUE TITLE
Development status?

### ISSUE THREAD

**Issue by jadestorm** [tykeal/puppet-sslmgmt#15]
Hi @tykeal !  I noticed that there hasn't been much development on this in quite some time so I wanted to ask you if you are still working with this module before potentially submitting some pull requests.  If you would prefer not to work with it anymore, I could always fork my own version and potentially pop that up on PuppetForge, but I don't usually like to do that unless the original author isn't really interested in maintaining anymore.  =)

I made a few fixes on my fork, and I am working on some functionality that may be considered a tad bizarre until I show a use case, but wanted to check in before I submit some PRs and get a conversation started.

Thanks!

**Comment by tykeal** [comment]
It's not that I'm not interested in maintaining it. It's just that I've had no need to make changes as it's working for us!

I'm also no longer working as a sysadmin most of the time so my time to focus on this is far, far less than when I originally wrote it.

So, I'm still open to PRs, but it looks like I need to fix the tests as there was a PR raised the other day and all tests are failing (probably because I haven't looked at it in forever).

**Comment by jadestorm** [comment]
Awesome  =)  Yeah I just wanted to check in first -- I need to do some work on my in-progress stuff but I'll submit some PRs once I get things settled!  Thanks!  (going to go ahead and close this one!)
